select * from dbo.EMPLOYEES

select * from dbo.EMPLOYESS_DIPT

select FIRST_NAME,EMAIL,DEPARTMENT from EMPLOYEES inner join EMPLOYESS_DIPT on EMPLOYEES.ID=EMPLOYESS_DIPT.ID

select EMPLOYEES.FIRST_NAME,EMPLOYESS_DIPT.ID, EMPLOYESS_DIPT.DEPARTMENT from EMPLOYEES left join EMPLOYESS_DIPT on EMPLOYEES.ID=EMPLOYESS_DIPT.ID 
order by EMPLOYEES.FIRST_NAME

select EMPLOYESS_DIPT.ID,EMPLOYESS_DIPT.JOIN_DATE, EMPLOYEES.FIRST_NAME,EMPLOYEES.EMAIL from EMPLOYESS_DIPT Right join EMPLOYEES on EMPLOYESS_DIPT.ID=EMPLOYEES.ID
order by EMPLOYESS_DIPT.ID

select EMPLOYEES.FIRST_NAME,EMPLOYEES.LAST_NAME,EMPLOYEES.EMAIL,EMPLOYEES.ADDRESSES,EMPLOYEES.PHONE, EMPLOYEES.SALARY, EMPLOYESS_DIPT.DEPARTMENT, EMPLOYESS_DIPT.DEPARTMENT,EMPLOYESS_DIPT.JOIN_DATE from EMPLOYEES full outer join EMPLOYESS_DIPT
on EMPLOYEES.ID=EMPLOYESS_DIPT.ID order by EMPLOYEES.FIRST_NAME

select EMPLOYEES.FIRST_NAME,EMPLOYESS_DIPT. DEPARTMENT from EMPLOYEES,EMPLOYESS_DIPT where EMPLOYEES.ID <> EMPLOYESS_DIPT.ID order by EMPLOYEES.FIRST_NAME